apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: aat-postgres
  name: aat-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
