apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: debezium
  name: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: debezium
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: debezium
    spec:
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS
              value: aat-kafka:29092
            - name: CONFIG_STORAGE_TOPIC
              value: debezium_connect_config
            - name: GROUP_ID
              value: "1"
            - name: LOG_LEVEL
              value: WARN
            - name: OFFSET_STORAGE_TOPIC
              value: debezium_connect_offset
            - name: STATUS_STORAGE_TOPIC
              value: debezium_connect_status
          image: 'debezium/connect:'
          livenessProbe:
            exec:
              command:
                - curl
                - --silent
                - --fail
                - -X
                - GET
                - http://localhost:8083/connectors
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: aat-debezium
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
