apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: debezium-ui
  name: debezium-ui
spec:
  ports:
    - name: "6969"
      port: 6969
      targetPort: 8080
  selector:
    io.kompose.service: debezium-ui
