apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: CREATE_TOPICS
              value: debezium_connect_config:1:1:compact,debezium_connect_offsets:1:1:compact,debezium_connect_status:1:1:compact
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://aat-kafka:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://aat-kafka:29092,PLAINTEXT_HOST://aat-kafka:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "1"
            - name: LOG_LEVEL
              value: WARN
            - name: NODE_ID
              value: "1"
            - name: ZOOKEEPER_CONNECT
              value: aat-zookeeper:2181
          image: 'debezium/kafka:'
          livenessProbe:
            exec:
              command:
                - ./bin/kafka-topics.sh
                - --list
                - --bootstrap-server
                - aat-kafka:29092
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: aat-kafka
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 29092
              protocol: TCP
      restartPolicy: Always
